### ISSUE TITLE
Valhalla instance not starting after builder finishes

### ISSUE THREAD

**Issue by julianflapper** [itayankri/valhalla-operator#86]
Hi,

I am trying to set up the operator and instances, and get stuck after building has completed.

The last log message of the builder is: 
`[INFO] Finished with 87683 nodes`
and I would expect a Valhalla pod to start up afterwards, but nothing happens. 

Running `kubectl get all -n valhalla-system` returns the following, showing no indication of a Valhalla pod attempting to start up:
```
> kubectl get all -n valhalla-system
NAME                                              READY   STATUS    RESTARTS   AGE
pod/valhalla-builder-gv98m                        1/1     Running   0          5m12s
pod/valhalla-controller-manager-775677bc4-zlr9b   2/2     Running   0          6m22s

NAME                                                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/valhalla-controller-manager-metrics-service   ClusterIP   10.0.41.170   <none>        8443/TCP   6m23s

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/valhalla-controller-manager   1/1     1            1           6m23s

NAME                                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/valhalla-controller-manager-775677bc4   1         1         1       6m23s

NAME                         COMPLETIONS   DURATION   AGE
job.batch/valhalla-builder   0/1           5m12s      5m12s
>
```

I am running the latest version of the operator (1.4.0), on Azure Kubernets Service (AKS) version 1.25.6.
The StorageClass I am using is "Azure File CSI standard" with retain policy and "ReadWriteMany". 

Neither the operator nor the builder are showing any errors.

Is there anything I can do to solve this or debug the issue?

**Comment by julianflapper** [comment]
Turns out the `valhalla_build_admins` step takes a long time (1 hour+?) without any status updates inbetween, and 4GB wasn't enough to build a OSM file of 1.2GB (Netherlands). So it seems solved.

But now I get the same issue as https://github.com/itayankri/valhalla-operator/issues/81

**Comment by itayankri** [comment]
Let's move the discussion to #81, closing this one.
